---
on:
  push:
    branches:
      - master

jobs:
  push-to-pages:
    needs: pre-ci
    runs-on: ubuntu-latest

    steps:
      - run: echo "::set-output name=output::$(helm package charts/vouch)"
        id: helm_package

      - uses: actions/upload-artifact@v2
        with:
          path: artifacts/*.tgz
